<!DOCTYPE html>
<html lang="tr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="css/style1.css">
<title>Giris Sayfasi</title>
</head>
<body>
<div class="container">
<div class="box form-box">
<header>GİRİŞ</header>
<form action="" method="post">
<div class="field input">
<label for="E-mail">E-mail</label>
<input type="email" name="E-mail" id="E-mail" required>
</div>
<div class="field input">
<label for="Sifre">Sifre</label>
<input type="password" name="Sifre" id="Sifre" required>
</div>
<div class="field">
<input type="submit" name="submit" class="buton" value="Giris Yap" required>
</div>
</form>
</div>
</div>
</body>
</html>